# Generated by Django 3.1.6 on 2021-02-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specializationId', models.AutoField(primary_key=True, serialize=False)),
                ('specializationName', models.CharField(max_length=22)),
                ('specializationDetail', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorBmdcId', models.CharField(max_length=22)),
                ('doctorDesignation', models.CharField(max_length=55)),
                ('doctorSpecializationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialization')),
                ('doctorUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
