# Generated by Django 3.1.6 on 2021-03-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('visiting_schedule', '0002_auto_20210304_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentPaymentCredential', models.CharField(max_length=11)),
                ('appointmentPatientSymptomNote', models.CharField(max_length=111)),
                ('appointmentTime', models.TimeField()),
                ('appointmentIsConfirmed', models.BooleanField()),
                ('appointmentIsCanceled', models.BooleanField()),
                ('appointmentIsVisited', models.BooleanField()),
                ('appointmentDate', models.DateField()),
                ('appointmentPatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('appointmentVisitingScheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiting_schedule.visitingschedule')),
            ],
        ),
    ]
