# Generated by Django 3.1.6 on 2021-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210322_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsCanceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsVisited',
            field=models.BooleanField(default=False),
        ),
    ]
