# Generated by Django 3.1.6 on 2021-03-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20210322_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsCanceled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsConfirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIsVisited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPatientSymptomNote',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPaymentCredential',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
