# Generated by Django 3.1.6 on 2021-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210323_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPatientSymptomNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPaymentCredential',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
