# Generated by Django 3.1.6 on 2021-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210323_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPatientSymptomNote',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentPaymentCredential',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
