# Generated by Django 3.1.6 on 2021-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20210323_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentType',
            field=models.CharField(choices=[('old', 'old'), ('report', 'report'), ('new', 'new')], default='name', max_length=11),
            preserve_default=False,
        ),
    ]
