# Generated by Django 3.1.6 on 2021-02-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('locationAdderssDetail', models.CharField(max_length=55)),
                ('locationLongitude', models.DecimalField(decimal_places=22, max_digits=33)),
                ('locationLatitude', models.DecimalField(decimal_places=22, max_digits=33)),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('chamberId', models.AutoField(primary_key=True, serialize=False)),
                ('chamberLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamber.location')),
                ('chamberUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
