# Generated by Django 3.1.6 on 2021-04-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientquery'),
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuery',
            fields=[
                ('askedQueryId', models.AutoField(primary_key=True, serialize=False)),
                ('askedQueryAnswer', models.TextField()),
                ('chamberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamber.chamber')),
                ('queryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientquery')),
            ],
        ),
    ]
