# Generated by Django 3.1.6 on 2021-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_askedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askedquery',
            name='askedQueryAnswer',
            field=models.TextField(blank=True),
        ),
    ]
