# Generated by Django 3.1.6 on 2021-05-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0006_auto_20210323_2030'),
        ('patient', '0002_patientquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('instructionId', models.AutoField(primary_key=True, serialize=False)),
                ('instructionDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineId', models.AutoField(primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=33)),
                ('medicineCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.company')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineForm',
            fields=[
                ('formId', models.AutoField(primary_key=True, serialize=False)),
                ('formName', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('patientHistoryId', models.AutoField(primary_key=True, serialize=False)),
                ('patientHistoryDeatils', models.TextField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestionId', models.AutoField(primary_key=True, serialize=False)),
                ('suggestionDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('patientHistoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.patienthistory')),
                ('suggestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('prescribedMedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=22)),
                ('frequency', models.CharField(max_length=22)),
                ('duration', models.CharField(max_length=22)),
                ('instructionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.instruction')),
                ('medicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.medicine')),
                ('prescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicineFormId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.medicineform'),
        ),
    ]
