# Generated by Django 3.1.6 on 2021-05-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicineCompany',
            new_name='medicineCompanyId',
        ),
    ]
