# Generated by Django 3.1.6 on 2021-05-08 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20210508_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patientHistoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.patienthistory'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='suggestionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.suggestion'),
        ),
    ]
