# Generated by Django 3.1.6 on 2021-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20210508_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='patientHistoryDeatils',
            new_name='patientHistoryDetails',
        ),
    ]
