# Generated by Django 3.1.6 on 2021-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_auto_20210520_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineform',
            name='formName',
            field=models.CharField(choices=[('tablet', 'tablet'), ('liquid', 'liquid'), ('capsule', 'capsule')], max_length=22),
        ),
    ]
