# Generated by Django 3.1.6 on 2021-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userPhoneNumber', models.CharField(max_length=22, unique=True)),
                ('userName', models.CharField(max_length=55)),
                ('userRole', models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('chamber', 'chamber'), ('pathology', 'pathology'), ('admin', 'admin')], max_length=22)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
