# Generated by Django 3.1.6 on 2021-05-20 22:42

from django.db import migrations, models
import django.db.models.deletion
import patient_report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_patientquery'),
        ('pathology', '0001_initial'),
    ]

    
