# Generated by Django 3.1.6 on 2021-05-20 22:42

from django.db import migrations, models
import django.db.models.deletion
import patient_report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_patientquery'),
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('patientReportId', models.AutoField(primary_key=True, serialize=False)),
                ('sendDate', models.DateTimeField(auto_now_add=True)),
                ('filePath', models.FileField(upload_to=patient_report.models.PatientReport.user_directory_path)),
                ('pathologyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.pathology')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
