# Generated by Django 3.1.6 on 2021-05-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0002_auto_20210521_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
