# Generated by Django 3.1.6 on 2021-03-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('datsOfWeekId', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('yuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('feeId', models.AutoField(primary_key=True, serialize=False)),
                ('oldFee', models.IntegerField()),
                ('newFee', models.IntegerField()),
                ('reportFee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitingSchedule',
            fields=[
                ('visitingScheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('startAt', models.TimeField()),
                ('endAt', models.TimeField()),
                ('maxPatient', models.IntegerField()),
                ('isCanceled', models.BooleanField()),
                ('isDeleted', models.BooleanField()),
                ('visitingScheduleChamberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamber.chamber')),
                ('visitingScheduleDaysOfWeekId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiting_schedule.daysofweek')),
                ('visitingScheduleDoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('visitingScheduleFeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiting_schedule.fee')),
            ],
        ),
    ]
