# Generated by Django 3.1.6 on 2021-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_schedule', '0002_auto_20210304_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingschedule',
            name='visitingScheduleAdditionalInformation',
            field=models.TextField(default='make payment in bkash number 0195396300 from send money option'),
            preserve_default=False,
        ),
    ]
