# Generated by Django 3.1.6 on 2021-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_schedule', '0003_visitingschedule_visitingscheduleadditionalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='day',
            field=models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=10, unique=True),
        ),
    ]
