# Generated by Django 3.1.6 on 2021-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_schedule', '0004_auto_20210604_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingschedule',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitingschedule',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
